apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PROJECT_NAME: kube-essentials
  SECRET_KEY: verysecret
  FIRST_SUPERUSER: admin@i.com
  FIRST_SUPERUSER_PASSWORD: ImBest0fTheBest # Should be at least 8 characters
  POSTGRES_SERVER: postgres-postgresql.postgres.svc.cluster.local # Use the postgres-postgresql service located in the postrges namespace
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: RwnUHSeMC8 # Find it in the secret in the postgres namespace
